### ISSUE TITLE
Updated telemetry stack needed - Separate what needs to run on server vs. edge appliance

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/performance-test#2]
The server that hosts the Influxdb and Grafana dashboard will be separate from the edge appliance that spins up for the performance tests.  The docker-compose should be written to separate the server based docker components from the appliance based.

**Comment by jamesrgregg** [comment]
Also.. we will need to see the actual IAC that LF uses to understand how the security group rules are going to be defined for the required server side dependencies.

**Comment by cloudxxx8** [comment]
@jamesrgregg different server could still leverage the same docker-compose file.  we just need to use different docker-compose command to achieve it.

**Comment by jamesrgregg** [comment]
initial implementation is on Jenkins with build nodes.  closing issue as non-issue in this initial implementation of the performance-tests jenkins jobs.
