### ISSUE TITLE
Need visibility to the Infrastructure as Code for the EdgeX TIG stack 

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/performance-test#3]
The performance testing needs to comprehend the security group rules in play on the cloud hosted infrastructure since the Grafana dashboard will be exposed publicly.
 - What port will Grafana be exposed publicly?

The docker-compose that runs the Docker components on the cloud hosted infrastructure needs to be aligned with the exposed port which serves Grafana dashboard.
 - What is the host port that will map to the running container for grafana?

**Comment by cloudxxx8** [comment]
By default, the Grafana port is 3000
https://github.com/edgexfoundry-holding/performance-test/blob/master/docker-compose.yml#L7

**Comment by jamesrgregg** [comment]
@cloudxxx8 @cherrycl the endpoint that you will use for your telegraf container is: 
  urls = ["http://stats.edgexfoundry.org:8086"] # required

**Comment by cherrycl** [comment]
> @cloudxxx8 @cherrycl the endpoint that you will use for your telegraf container is:
> urls = ["http://stats.edgexfoundry.org:8086"] # required

Thank you.

**Comment by jamesrgregg** [comment]
That endpoint is only accessible from LF networks

**Comment by jamesrgregg** [comment]
non-issue now that the infrastructure has been landed.
