### ISSUE TITLE
docker-compose file error and add telegraf config file

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/performance-test#5]
1. docker-compose file can't be executed.
2. Missing telegraf config file.

**Comment by jamesrgregg** [comment]
Is this the endpoint of the Influxdb on the cloud hosted Influxdb?
If so, how will it be configured for the performance test that needs to send telemetry / performance data to the cloud hosted Influxdb?

https://github.com/edgexfoundry-holding/performance-test/blob/master/telegraf/telegraf.conf#L16

**Comment by cherrycl** [comment]
@jamesrgregg Currently, Grafana, Influxdb, and Telegraf is in the same docker-compose file . The endpoint of the influxdb is based on the designed which set on docker-compose file.
If someone runs the performance test by current script, he/she  will failed by this issue.

Next, we will discuss new TIG stack for Jenkins integration. Like you mentioned on #2 .
At that time, the endpoint of the influxdb may not different with the current setting.

**Comment by jamesrgregg** [comment]
closing as this is now an non-issue with the infrastructure landed
